# HomeHub one-line installer for Windows (PowerShell)
#   irm https://raw.githubusercontent.com/alamanna993/home-hub/main/install.ps1 | iex
$ErrorActionPreference = 'Stop'

$Repo = 'https://github.com/alamanna993/home-hub.git'
$Dir = if ($env:HOMEHUB_DIR) { $env:HOMEHUB_DIR } else { 'home-hub' }

function Say($msg) { Write-Host "[homehub] $msg" -ForegroundColor Cyan }

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) { throw 'Docker is required — install Docker Desktop first.' }
if (-not (Get-Command git -ErrorAction SilentlyContinue)) { throw 'git is required.' }

if (Test-Path "$Dir/.git") {
  Say "Existing install found in ./$Dir — updating..."
  git -C $Dir pull --ff-only
} else {
  Say "Cloning HomeHub into ./$Dir ..."
  git clone --depth 1 $Repo $Dir
}
Set-Location $Dir

if (-not (Test-Path .env)) {
  Say 'Generating .env with random secrets...'
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  function Gen-Secret($bytes) {
    $buf = New-Object byte[] $bytes; $rng.GetBytes($buf)
    ($buf | ForEach-Object { $_.ToString('x2') }) -join ''
  }
  @"
# Generated by install.ps1 — see .env.example for all options
DB_PASSWORD=$(Gen-Secret 16)
SECRET_KEY=$(Gen-Secret 32)

# Uncomment to store the database on a specific folder (e.g. a NAS share):
#DATA_PATH=D:/homehub/db
#BACKUP_PATH=E:/backup/homehub

# Uncomment if ports 3000/8000 are taken on this host:
#FRONTEND_PORT=3000
#BACKEND_PORT=8000
"@ | Set-Content .env -Encoding utf8
} else {
  Say 'Keeping existing .env'
}

Say 'Pulling prebuilt images (falls back to building locally)...'
docker compose pull 2>$null
if ($LASTEXITCODE -eq 0) { docker compose up -d } else {
  Say 'Pull unavailable — building images locally (first build takes a few minutes)...'
  docker compose up -d --build
}

$port = (Select-String -Path .env -Pattern '^FRONTEND_PORT=(\d+)' -ErrorAction SilentlyContinue).Matches.Groups[1].Value
if (-not $port) { $port = 3000 }
Say ''
Say '✅ HomeHub is starting!'
Say "   Open:    http://localhost:$port"
Say '   Sign in: admin / admin  — the setup wizard takes it from there.'
