#!/usr/bin/env bash
# HomeHub one-line installer
#   curl -fsSL https://raw.githubusercontent.com/alamanna993/home-hub/main/install.sh | bash
# Works on Linux, macOS, WSL, and most NAS boxes with Docker + git installed.
set -euo pipefail

REPO="https://github.com/alamanna993/home-hub.git"
DIR="${HOMEHUB_DIR:-home-hub}"

say() { printf '\033[1;36m[homehub]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[homehub]\033[0m %s\n' "$*" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || die "Docker is required — install it first: https://docs.docker.com/get-docker/"
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is required (the 'docker compose' command)."
command -v git >/dev/null 2>&1 || die "git is required."

if [ -d "$DIR/.git" ]; then
  say "Existing install found in ./$DIR — updating..."
  git -C "$DIR" pull --ff-only
else
  say "Cloning HomeHub into ./$DIR ..."
  git clone --depth 1 "$REPO" "$DIR"
fi
cd "$DIR"

gen_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$1"
  else
    (LC_ALL=C tr -dc 'a-f0-9' </dev/urandom | head -c "$(( $1 * 2 ))") || true
  fi
}

if [ ! -f .env ]; then
  say "Generating .env with random secrets..."
  cat > .env <<EOF
# Generated by install.sh — see .env.example for all options
DB_PASSWORD=$(gen_secret 16)
SECRET_KEY=$(gen_secret 32)

# Uncomment to store the database on a specific folder (e.g. a NAS share):
#DATA_PATH=/volume1/docker/homehub/db
#BACKUP_PATH=/volume1/backup/homehub

# Uncomment if ports 3000/8000 are taken on this host:
#FRONTEND_PORT=3000
#BACKEND_PORT=8000
EOF
else
  say "Keeping existing .env"
fi

say "Pulling prebuilt images (falls back to building locally)..."
if docker compose pull 2>/dev/null; then
  docker compose up -d
else
  say "Pull unavailable — building images locally (first build takes a few minutes)..."
  docker compose up -d --build
fi

PORT="$(grep -E '^FRONTEND_PORT=' .env | cut -d= -f2 || true)"
say ""
say "✅ HomeHub is starting!"
say "   Open:    http://localhost:${PORT:-3000}"
say "   Sign in: admin / admin  — the setup wizard takes it from there."
